#!/bin/bash
# Quick verification script for game flow fixes

echo "=========================================="
echo "VC Card Game - Flow Verification"
echo "=========================================="
echo ""

echo "Checking files exist..."
[ -f "stage_actions.html" ] && echo "✓ stage_actions.html found" || echo "✗ stage_actions.html missing"
[ -f "web_wrangler_fixed.py" ] && echo "✓ web_wrangler_fixed.py found" || echo "✗ web_wrangler_fixed.py missing"
[ -f "web_game.py" ] && echo "✓ web_game.py found" || echo "✗ web_game.py found"
echo ""

echo "Checking Python syntax..."
python3 -m py_compile web_game.py web_wrangler_fixed.py 2>&1 && echo "✓ Python files compile successfully" || echo "✗ Python syntax errors"
echo ""

echo "Checking critical functions exist..."
grep -q "function doEnter()" stage_actions.html && echo "✓ doEnter() function found" || echo "✗ doEnter() missing"
grep -q "function pollForStage1Ready()" stage_actions.html && echo "✓ pollForStage1Ready() function found" || echo "✗ pollForStage1Ready() missing"
grep -q "const needsReset = STAGE === 3" stage_actions.html && echo "✓ Conditional reset logic found" || echo "✗ Reset logic missing"
grep -q "Game complete! Closing in" web_wrangler_fixed.py && echo "✓ Auto-close countdown found" || echo "✗ Countdown missing"
echo ""

echo "Checking key behaviors..."
grep -q "pollForStage1Ready()" stage_actions.html && echo "✓ Enter button calls pollForStage1Ready" || echo "✗ Poll function not called"
grep -q "window.close()" web_wrangler_fixed.py && echo "✓ Tab close logic implemented" || echo "✗ Tab close missing"
grep -q "Browser security prevented auto-close" web_wrangler_fixed.py && echo "✓ Fallback message found" || echo "✗ Fallback missing"
echo ""

echo "=========================================="
echo "Manual Testing Required:"
echo "=========================================="
echo ""
echo "1. Start server:"
echo "   python3 web_game.py"
echo ""
echo "2. Test Case 1: First Game"
echo "   - Open http://localhost:8765/"
echo "   - Enter name, click Enter"
echo "   - Verify: Game starts within 1-2 seconds"
echo "   - Verify: NO reload to login page"
echo ""
echo "3. Test Case 2: Complete Game"
echo "   - Play through Stage 1 → Stage 2"
echo "   - Click 'Quit Game' on results"
echo "   - Verify: Countdown shows (3, 2, 1)"
echo "   - Verify: Tab closes or shows fallback"
echo ""
echo "4. Test Case 3: Second Game"
echo "   - Open new tab: http://localhost:8765/"
echo "   - Enter name, click Enter"
echo "   - Verify: Game starts normally"
echo ""
echo "All tests should pass for complete verification."
echo ""
